pipeline {
    agent any
    environment{
        AWS_ACCESS_KEY_ID = credentials('AWS-creds')
        AWS_SECRET_ACCESS_KEY = credentials('AWS-creds')
    }
    stages {
        stage('checkout') {
            git (
                url: '',
                branch: 'master'
            )
        }
    }
}
